"""initial schema

Revision ID: 0001
Revises:
Create Date: 2026-09-26 14:16:07.815050

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

import ttk.db.models

# revision identifiers, used by Alembic.
revision: str = "0001"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "ingestion_runs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("provider", sa.String(length=50), nullable=False),
        sa.Column("kind", sa.String(length=30), nullable=False),
        sa.Column("sport", sa.String(length=10), nullable=False),
        sa.Column("started_at", ttk.db.models.UTCDateTime(), nullable=False),
        sa.Column("finished_at", ttk.db.models.UTCDateTime(), nullable=True),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("records_written", sa.Integer(), nullable=False),
        sa.Column("skipped", sa.JSON(), nullable=True),
        sa.Column("error", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "model_versions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("version", sa.String(length=30), nullable=False),
        sa.Column("sport", sa.String(length=10), nullable=False),
        sa.Column("market", sa.String(length=20), nullable=False),
        sa.Column("algorithm", sa.String(length=50), nullable=False),
        sa.Column("features", sa.JSON(), nullable=True),
        sa.Column("training_window", sa.String(length=50), nullable=True),
        sa.Column("validation_window", sa.String(length=50), nullable=True),
        sa.Column("calibration_method", sa.String(length=30), nullable=True),
        sa.Column("brier_score", sa.Float(), nullable=True),
        sa.Column("log_loss", sa.Float(), nullable=True),
        sa.Column("historical_roi", sa.Float(), nullable=True),
        sa.Column("historical_clv", sa.Float(), nullable=True),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("health", sa.String(length=20), nullable=False),
        sa.Column("created_at", ttk.db.models.UTCDateTime(), nullable=False),
        sa.Column("deployed_at", ttk.db.models.UTCDateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name", "version"),
    )
    op.create_table(
        "sportsbooks",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("key", sa.String(length=50), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("key"),
    )
    op.create_table(
        "teams",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("sport", sa.String(length=10), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("abbreviation", sa.String(length=10), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("sport", "name"),
    )
    op.create_table(
        "games",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("sport", sa.String(length=10), nullable=False),
        sa.Column("season", sa.Integer(), nullable=True),
        sa.Column("home_team_id", sa.Integer(), nullable=False),
        sa.Column("away_team_id", sa.Integer(), nullable=False),
        sa.Column("commence_time", ttk.db.models.UTCDateTime(), nullable=False),
        sa.Column("neutral_site", sa.Boolean(), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("home_score", sa.Integer(), nullable=True),
        sa.Column("away_score", sa.Integer(), nullable=True),
        sa.Column("updated_at", ttk.db.models.UTCDateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["away_team_id"],
            ["teams.id"],
        ),
        sa.ForeignKeyConstraint(
            ["home_team_id"],
            ["teams.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("games", schema=None) as batch_op:
        batch_op.create_index("ix_games_sport_commence", ["sport", "commence_time"], unique=False)

    op.create_table(
        "injury_reports",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("sport", sa.String(length=10), nullable=False),
        sa.Column("team_id", sa.Integer(), nullable=True),
        sa.Column("player_name", sa.String(length=100), nullable=False),
        sa.Column("player_source_identifier", sa.String(length=100), nullable=True),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("injury_type", sa.String(length=100), nullable=True),
        sa.Column("expected_minutes", sa.Float(), nullable=True),
        sa.Column("estimated_impact", sa.Float(), nullable=True),
        sa.Column("provider", sa.String(length=50), nullable=False),
        sa.Column("source_timestamp", ttk.db.models.UTCDateTime(), nullable=True),
        sa.Column("observed_at", ttk.db.models.UTCDateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["team_id"],
            ["teams.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "parlays",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("created_at", ttk.db.models.UTCDateTime(), nullable=False),
        sa.Column("sportsbook_id", sa.Integer(), nullable=True),
        sa.Column("american_odds", sa.Float(), nullable=True),
        sa.Column("stake", sa.Float(), nullable=True),
        sa.Column("model_joint_probability", sa.Float(), nullable=True),
        sa.Column("correlation_risk", sa.String(length=20), nullable=True),
        sa.Column("result", sa.String(length=10), nullable=False),
        sa.Column("profit_loss", sa.Float(), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(
            ["sportsbook_id"],
            ["sportsbooks.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "team_aliases",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("provider", sa.String(length=50), nullable=False),
        sa.Column("sport", sa.String(length=10), nullable=False),
        sa.Column("alias", sa.String(length=100), nullable=False),
        sa.Column("team_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["team_id"],
            ["teams.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("provider", "sport", "alias"),
    )
    op.create_table(
        "game_source_ids",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("provider", sa.String(length=50), nullable=False),
        sa.Column("source_identifier", sa.String(length=100), nullable=False),
        sa.Column("game_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["game_id"],
            ["games.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("provider", "source_identifier"),
    )
    op.create_table(
        "odds_snapshots",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("game_id", sa.Integer(), nullable=False),
        sa.Column("sportsbook_id", sa.Integer(), nullable=False),
        sa.Column("market", sa.String(length=20), nullable=False),
        sa.Column("selection", sa.String(length=10), nullable=False),
        sa.Column("line", sa.Float(), nullable=True),
        sa.Column("american_odds", sa.Float(), nullable=False),
        sa.Column("decimal_odds", sa.Float(), nullable=False),
        sa.Column("implied_probability", sa.Float(), nullable=False),
        sa.Column("provider", sa.String(length=50), nullable=False),
        sa.Column("source_timestamp", ttk.db.models.UTCDateTime(), nullable=True),
        sa.Column("observed_at", ttk.db.models.UTCDateTime(), nullable=False),
        sa.Column("ingestion_run_id", sa.Integer(), nullable=False),
        sa.Column("data_version", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["game_id"],
            ["games.id"],
        ),
        sa.ForeignKeyConstraint(
            ["ingestion_run_id"],
            ["ingestion_runs.id"],
        ),
        sa.ForeignKeyConstraint(
            ["sportsbook_id"],
            ["sportsbooks.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("odds_snapshots", schema=None) as batch_op:
        batch_op.create_index(
            "ix_odds_lookup",
            ["game_id", "market", "selection", "sportsbook_id", "observed_at"],
            unique=False,
        )

    op.create_table(
        "predictions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("game_id", sa.Integer(), nullable=False),
        sa.Column("model_version_id", sa.Integer(), nullable=False),
        sa.Column("market", sa.String(length=20), nullable=False),
        sa.Column("selection", sa.String(length=10), nullable=False),
        sa.Column("line", sa.Float(), nullable=True),
        sa.Column("probability", sa.Float(), nullable=False),
        sa.Column("push_probability", sa.Float(), nullable=False),
        sa.Column("uncertainty", sa.String(length=20), nullable=False),
        sa.Column("data_quality", sa.String(length=20), nullable=False),
        sa.Column("features", sa.JSON(), nullable=True),
        sa.Column("inputs_as_of", ttk.db.models.UTCDateTime(), nullable=False),
        sa.Column("created_at", ttk.db.models.UTCDateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["game_id"],
            ["games.id"],
        ),
        sa.ForeignKeyConstraint(
            ["model_version_id"],
            ["model_versions.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("predictions", schema=None) as batch_op:
        batch_op.create_index(
            "ix_predictions_game", ["game_id", "market", "created_at"], unique=False
        )

    op.create_table(
        "bets",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("placed_at", ttk.db.models.UTCDateTime(), nullable=False),
        sa.Column("sport", sa.String(length=10), nullable=False),
        sa.Column("game_id", sa.Integer(), nullable=True),
        sa.Column("parlay_id", sa.Integer(), nullable=True),
        sa.Column("prediction_id", sa.Integer(), nullable=True),
        sa.Column("model_version_id", sa.Integer(), nullable=True),
        sa.Column("sportsbook_id", sa.Integer(), nullable=True),
        sa.Column("market", sa.String(length=20), nullable=False),
        sa.Column("selection", sa.String(length=10), nullable=False),
        sa.Column("description", sa.String(length=200), nullable=False),
        sa.Column("line", sa.Float(), nullable=True),
        sa.Column("american_odds", sa.Float(), nullable=False),
        sa.Column("model_probability", sa.Float(), nullable=True),
        sa.Column("market_probability", sa.Float(), nullable=True),
        sa.Column("edge", sa.Float(), nullable=True),
        sa.Column("expected_value", sa.Float(), nullable=True),
        sa.Column("stake", sa.Float(), nullable=True),
        sa.Column("result", sa.String(length=10), nullable=False),
        sa.Column("profit_loss", sa.Float(), nullable=True),
        sa.Column("closing_line", sa.Float(), nullable=True),
        sa.Column("closing_american_odds", sa.Float(), nullable=True),
        sa.Column("closing_no_vig_probability", sa.Float(), nullable=True),
        sa.Column("clv", sa.Float(), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(
            ["game_id"],
            ["games.id"],
        ),
        sa.ForeignKeyConstraint(
            ["model_version_id"],
            ["model_versions.id"],
        ),
        sa.ForeignKeyConstraint(
            ["parlay_id"],
            ["parlays.id"],
        ),
        sa.ForeignKeyConstraint(
            ["prediction_id"],
            ["predictions.id"],
        ),
        sa.ForeignKeyConstraint(
            ["sportsbook_id"],
            ["sportsbooks.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###
    _create_immutability_triggers()


# Append-only tables: history must never be rewritten (docs/MODEL-GOVERNANCE.md).
IMMUTABLE_TABLES = ("odds_snapshots", "injury_reports", "predictions")


def _create_immutability_triggers() -> None:
    if op.get_bind().dialect.name != "sqlite":
        raise NotImplementedError("Add immutability triggers for this database dialect")
    for table in IMMUTABLE_TABLES:
        for action in ("UPDATE", "DELETE"):
            op.execute(
                f"CREATE TRIGGER {table}_no_{action.lower()} BEFORE {action} ON {table} "
                f"BEGIN SELECT RAISE(ABORT, '{table} is append-only'); END"
            )


def downgrade() -> None:
    """Downgrade schema."""
    for table in IMMUTABLE_TABLES:
        for action in ("update", "delete"):
            op.execute(f"DROP TRIGGER IF EXISTS {table}_no_{action}")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("bets")
    with op.batch_alter_table("predictions", schema=None) as batch_op:
        batch_op.drop_index("ix_predictions_game")

    op.drop_table("predictions")
    with op.batch_alter_table("odds_snapshots", schema=None) as batch_op:
        batch_op.drop_index("ix_odds_lookup")

    op.drop_table("odds_snapshots")
    op.drop_table("game_source_ids")
    op.drop_table("team_aliases")
    op.drop_table("parlays")
    op.drop_table("injury_reports")
    with op.batch_alter_table("games", schema=None) as batch_op:
        batch_op.drop_index("ix_games_sport_commence")

    op.drop_table("games")
    op.drop_table("teams")
    op.drop_table("sportsbooks")
    op.drop_table("model_versions")
    op.drop_table("ingestion_runs")
    # ### end Alembic commands ###
