"""nfl history: reported lines, week, season type

Revision ID: 0003
Revises: 0002
Create Date: 2026-09-26 15:12:45.573842

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

import ttk.db.models

# revision identifiers, used by Alembic.
revision: str = "0003"
down_revision: str | Sequence[str] | None = "0002"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "reported_lines",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("game_id", sa.Integer(), nullable=False),
        sa.Column("provider", sa.String(length=50), nullable=False),
        sa.Column("home_spread", sa.Float(), nullable=True),
        sa.Column("home_spread_odds", sa.Float(), nullable=True),
        sa.Column("away_spread_odds", sa.Float(), nullable=True),
        sa.Column("total", sa.Float(), nullable=True),
        sa.Column("over_odds", sa.Float(), nullable=True),
        sa.Column("under_odds", sa.Float(), nullable=True),
        sa.Column("home_moneyline", sa.Float(), nullable=True),
        sa.Column("away_moneyline", sa.Float(), nullable=True),
        sa.Column("imported_at", ttk.db.models.UTCDateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["game_id"], ["games.id"], name=op.f("fk_reported_lines_game_id_games")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_reported_lines")),
        sa.UniqueConstraint("game_id", "provider", name=op.f("uq_reported_lines_game_id_provider")),
    )
    with op.batch_alter_table("games", schema=None) as batch_op:
        batch_op.add_column(sa.Column("season_type", sa.String(length=4), nullable=True))
        batch_op.add_column(sa.Column("week", sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("games", schema=None) as batch_op:
        batch_op.drop_column("week")
        batch_op.drop_column("season_type")

    op.drop_table("reported_lines")
    # ### end Alembic commands ###
