"""nfl play-by-play aggregates and starters

Revision ID: 0004
Revises: 0003
Create Date: 2026-09-26 15:38:12.616451

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

import ttk.db.models

# revision identifiers, used by Alembic.
revision: str = "0004"
down_revision: str | Sequence[str] | None = "0003"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "game_starters",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("game_id", sa.Integer(), nullable=False),
        sa.Column("team_id", sa.Integer(), nullable=False),
        sa.Column("position", sa.String(length=5), nullable=False),
        sa.Column("player_id", sa.String(length=20), nullable=False),
        sa.Column("player_name", sa.String(length=100), nullable=True),
        sa.Column("provider", sa.String(length=50), nullable=False),
        sa.Column("imported_at", ttk.db.models.UTCDateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["game_id"], ["games.id"], name=op.f("fk_game_starters_game_id_games")
        ),
        sa.ForeignKeyConstraint(
            ["team_id"], ["teams.id"], name=op.f("fk_game_starters_team_id_teams")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_game_starters")),
        sa.UniqueConstraint(
            "game_id",
            "team_id",
            "position",
            "provider",
            name=op.f("uq_game_starters_game_id_team_id_position_provider"),
        ),
    )
    op.create_table(
        "qb_game_stats",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("game_id", sa.Integer(), nullable=False),
        sa.Column("team_id", sa.Integer(), nullable=False),
        sa.Column("player_id", sa.String(length=20), nullable=False),
        sa.Column("player_name", sa.String(length=100), nullable=True),
        sa.Column("provider", sa.String(length=50), nullable=False),
        sa.Column("dropbacks", sa.Integer(), nullable=False),
        sa.Column("qb_epa_total", sa.Float(), nullable=False),
        sa.Column("imported_at", ttk.db.models.UTCDateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["game_id"], ["games.id"], name=op.f("fk_qb_game_stats_game_id_games")
        ),
        sa.ForeignKeyConstraint(
            ["team_id"], ["teams.id"], name=op.f("fk_qb_game_stats_team_id_teams")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_qb_game_stats")),
        sa.UniqueConstraint(
            "game_id",
            "player_id",
            "provider",
            name=op.f("uq_qb_game_stats_game_id_player_id_provider"),
        ),
    )
    op.create_table(
        "team_game_stats",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("game_id", sa.Integer(), nullable=False),
        sa.Column("team_id", sa.Integer(), nullable=False),
        sa.Column("provider", sa.String(length=50), nullable=False),
        sa.Column("plays", sa.Integer(), nullable=False),
        sa.Column("epa_total", sa.Float(), nullable=False),
        sa.Column("successes", sa.Integer(), nullable=False),
        sa.Column("dropbacks", sa.Integer(), nullable=False),
        sa.Column("dropback_epa_total", sa.Float(), nullable=False),
        sa.Column("rushes", sa.Integer(), nullable=False),
        sa.Column("rush_epa_total", sa.Float(), nullable=False),
        sa.Column("imported_at", ttk.db.models.UTCDateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["game_id"], ["games.id"], name=op.f("fk_team_game_stats_game_id_games")
        ),
        sa.ForeignKeyConstraint(
            ["team_id"], ["teams.id"], name=op.f("fk_team_game_stats_team_id_teams")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_team_game_stats")),
        sa.UniqueConstraint(
            "game_id",
            "team_id",
            "provider",
            name=op.f("uq_team_game_stats_game_id_team_id_provider"),
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("team_game_stats")
    op.drop_table("qb_game_stats")
    op.drop_table("game_starters")
    # ### end Alembic commands ###
