"""bet tracker settlement fields

Revision ID: 0006
Revises: 0005
Create Date: 2026-09-26 16:42:35.280090

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

import ttk.db.models

# revision identifiers, used by Alembic.
revision: str = "0006"
down_revision: str | Sequence[str] | None = "0005"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("bets", schema=None) as batch_op:
        batch_op.add_column(sa.Column("closing_points_gained", sa.Float(), nullable=True))
        batch_op.add_column(sa.Column("model_push_probability", sa.Float(), nullable=True))
        batch_op.add_column(sa.Column("settled_at", ttk.db.models.UTCDateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("bets", schema=None) as batch_op:
        batch_op.drop_column("settled_at")
        batch_op.drop_column("model_push_probability")
        batch_op.drop_column("closing_points_gained")

    # ### end Alembic commands ###
