"""parlay lab fields

Revision ID: 0007
Revises: 0006
Create Date: 2026-09-26 16:56:59.581850

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

import ttk.db.models

# revision identifiers, used by Alembic.
revision: str = "0007"
down_revision: str | Sequence[str] | None = "0006"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("parlays", schema=None) as batch_op:
        batch_op.add_column(sa.Column("placed_at", ttk.db.models.UTCDateTime(), nullable=True))
        batch_op.add_column(sa.Column("market_joint_probability", sa.Float(), nullable=True))
        batch_op.add_column(sa.Column("expected_value", sa.Float(), nullable=True))
        batch_op.add_column(sa.Column("settled_at", ttk.db.models.UTCDateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("parlays", schema=None) as batch_op:
        batch_op.drop_column("settled_at")
        batch_op.drop_column("expected_value")
        batch_op.drop_column("market_joint_probability")
        batch_op.drop_column("placed_at")

    # ### end Alembic commands ###
